import { WorkoutPlan, type IWorkoutPlan } from "../models/workoutPlanModel.js";
import { Exercise } from "../models/exerciseModel.js";
import axios from "axios";
import { Types } from "mongoose";

const OLLAMA_URL = process.env.OLLAMA_URL || "http://localhost:11434/api/generate";

export const workoutPlanService = {
    /**
     * Create a workout plan
     */
    createPlan: async (data: any) => {
        const newPlan = new WorkoutPlan(data);
        await newPlan.save();
        return newPlan;
    },

    /**
     * Get user's workout plans
     */
    getUserPlans: async (userId: string) => {
        return await WorkoutPlan.find({ ownerId: userId }).sort({ createdAt: -1 });
    },

    /**
     * Get public templates or gym templates
     */
    getTemplates: async (gymId?: string) => {
        const query: any = { isTemplate: true };
        if (gymId) query.gymId = gymId;
        return await WorkoutPlan.find(query).sort({ createdAt: -1 });
    },

    /**
     * Clone a template for a user
     */
    clonePlan: async (templateId: string, userId: string) => {
        const template = await WorkoutPlan.findById(templateId);
        if (!template) throw new Error("Template not found");

        const newPlan = new WorkoutPlan({
            ...template.toObject(),
            _id: new Types.ObjectId(),
            ownerId: userId,
            isTemplate: false,
            name: `${template.name} (Copy)`
        });

        await newPlan.save();
        return newPlan;
    },

    /**
     * Auto-generate a workout plan using Ollama
     */
    generateWorkout: async (userId: string, preferences: { goal: string, level: string, daysPerWeek: number }) => {
        // 1. Fetch some exercises to provide context to the LLM
        const exercises = await Exercise.find({}).limit(20);
        const exercisesNames = exercises.map(e => e.name).join(", ");

        const prompt = `Generate a personalized workout plan for a user with the following preferences:
Goal: ${preferences.goal}
Level: ${preferences.level}
Days per week: ${preferences.daysPerWeek}

Available exercises: ${exercisesNames}

Return the plan in JSON format matching this structure:
{
  "name": "Personalized AI Plan",
  "description": "description here",
  "days": [
    {
      "dayNumber": 1,
      "title": "Day Title",
      "exercises": [
        { "exerciseName": "Exercise Name", "sets": 3, "reps": 12, "order": 1 }
      ]
    }
  ]
}
Only return the JSON. No other text.`;

        try {
            const response = await axios.post(OLLAMA_URL, {
                model: "mistral",
                prompt: prompt,
                stream: false,
                format: "json"
            });

            const responseText = response.data.response;
            let generatedData: any;
            try {
                generatedData = JSON.parse(responseText);
            } catch (parseErr) {
                console.error("Failed to parse Ollama response as JSON:", responseText);
                throw new Error("Invalid response from AI model");
            }

            // Support common nested structures some models use
            if (!generatedData.days && generatedData.plan) {
                generatedData = generatedData.plan;
            } else if (!generatedData.days && generatedData.workout_plan) {
                generatedData = generatedData.workout_plan;
            }

            if (!generatedData.days || !Array.isArray(generatedData.days)) {
                console.error("Ollama response missing days array:", generatedData);
                throw new Error("AI model failed to generate a valid plan structure");
            }

            // Map exercise names back to IDs
            const allExercises = await Exercise.find({});
            if (allExercises.length === 0) {
                throw new Error("Exercise library is empty. Please seed exercises first.");
            }
            const nameToId = new Map(allExercises.map(e => [e.name.toLowerCase(), e._id]));

            const finalDays = generatedData.days.map((day: any) => ({
                dayNumber: day.dayNumber || 1,
                title: day.title || "Workout Day",
                exercises: (day.exercises || []).map((ex: any) => ({
                    exerciseId: nameToId.get((ex.exerciseName || "").toLowerCase()) || allExercises[0]._id,
                    sets: ex.sets || 3,
                    reps: ex.reps || 12,
                    order: ex.order || 1
                }))
            }));

            const newPlan = new WorkoutPlan({
                ownerId: userId,
                name: generatedData.name || "Personalized AI Plan",
                description: generatedData.description || "Generated by FitMe AI",
                isTemplate: false,
                days: finalDays
            });

            await newPlan.save();
            return newPlan;
        } catch (err: any) {
            console.error("Ollama generation failed:", err.message);
            throw new Error("Failed to auto-generate workout plan");
        }
    },

    /**
     * Update a plan
     */
    updatePlan: async (planId: string, userId: string, updates: any) => {
        const plan = await WorkoutPlan.findOneAndUpdate(
            { _id: planId, ownerId: userId },
            { $set: updates },
            { new: true }
        );
        if (!plan) throw new Error("Plan not found or unauthorized");
        return plan;
    },

    /**
     * Delete a plan
     */
    deletePlan: async (planId: string, userId: string) => {
        const result = await WorkoutPlan.deleteOne({ _id: planId, ownerId: userId });
        if (result.deletedCount === 0) throw new Error("Plan not found or unauthorized");
        return true;
    }
};
